### ISSUE TITLE
Example code for client needed.

### ISSUE THREAD

**Issue by DaBlitzStein** [micro/kv-srv#1]
We need an example code for client to make easy to deploy clients for this tool.

**Comment by asim** [comment]
It's simple key-value {get, put, delete} via go-micro RPC. Call it like you would any other service. A client exists in the go-os library. Here's an example of its use https://github.com/micro/go-os/blob/master/examples/kv/kv.go. Do not rely on kv-srv as it architecture will likely change in the near future.
